#!/usr/bin/env sh
#
# git-new_branch
#
# Matt Guan
# move all changes to a clean branch, fast forward it to origin/master, and push it to origin
# usage: git new_branch {branch_name}

exists=`git branch --list $1`

if [[ -z $1 ]]; then
	echo "WARNING: Set branch name as argument"
	exit;
elif [[ $exists ]]; then
	echo "WARNING: Branch already exists ; did you mean to git checkout and use git magic?"
	exit;
else
	git stash
	git checkout -b $1
	echo "INFO : branch created"
	git fetch origin
	echo "INFO: fetched origin"
	git rebase origin/master
	git stash apply -q stash@{0}
	git stash drop
	echo "INFO : branch now at origin/master"
	git push -u -q origin $1
	echo "INFO : branch pushed to origin"
fi

