#!/usr/bin/env sh
#
# git-magic
#
# Matt Guan
# fast forward your entire branch to origin/master
# usage: git magic

git fetch origin
echo "INFO : fetched origin"
git stash
git rebase origin/master
git stash apply -q stash@{0}
git stash drop
echo "INFO : branch now at origin/master"
